Numpy documentation
https://numpy.org/doc/

In [261]:
import numpy as np

Data types & Attributes

In [262]:
# 1-dimensional

dt = np.array([1,2,3])
dt

array([1, 2, 3])

In [263]:
type(dt)

numpy.ndarray

In [264]:
# 2-dimensional 2x3

dt2 = np.array([[1., 2., 3.3],[4., 5., 6.5]])
dt2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [265]:
# 2-dimensional x array 2x3x3

dt3 = np.array([[[1, 2, 4],
               [3, 4, 5],
               [6, 7, 8]],
               
               [[2,3,4],
               [2,4,5],
               [3,5,6]]])
dt3

array([[[1, 2, 4],
        [3, 4, 5],
        [6, 7, 8]],

       [[2, 3, 4],
        [2, 4, 5],
        [3, 5, 6]]])

In [266]:
dt.size, dt2.size, dt3.size

(3, 6, 18)

In [267]:
type(dt), type(dt2), type(dt3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [268]:
# create dataframe from numpy 

import pandas as pd 

df = pd.DataFrame(dt2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

Numpy creates arrays

In [269]:
np_array = np.array([1, 2, 3])
np_array

array([1, 2, 3])

In [270]:
np_array.dtype

dtype('int32')

In [271]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [272]:
ones.dtype

dtype('float64')

In [273]:
type(ones)

numpy.ndarray

In [274]:
# zeros for change fill the array with 0

zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [275]:
range_array = np.arange(0, 20, 2)
range_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [276]:
# random array for randomize the array

random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[6, 0, 7, 7, 9],
       [2, 3, 8, 4, 5],
       [6, 0, 4, 6, 0]])

In [277]:
random_array.size, random_array.shape

(15, (3, 5))