Numpy documentation
https://numpy.org/doc/

In [95]:
import numpy as np

Data types & Attributes

In [96]:
# 1-dimensional

dt = np.array([1,2,3])
dt

array([1, 2, 3])

In [97]:
type(dt)

numpy.ndarray

In [98]:
# 2-dimensional 2x3

dt2 = np.array([[1., 2., 3.3],[4., 5., 6.5]])
dt2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [99]:
# 2-dimensional x array 2x3x3

dt3 = np.array([[[1, 2, 4],
               [3, 4, 5],
               [6, 7, 8]],
               
               [[2,3,4],
               [2,4,5],
               [3,5,6]]])
dt3

array([[[1, 2, 4],
        [3, 4, 5],
        [6, 7, 8]],

       [[2, 3, 4],
        [2, 4, 5],
        [3, 5, 6]]])

In [100]:
dt.size, dt2.size, dt3.size

(3, 6, 18)

In [101]:
type(dt), type(dt2), type(dt3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [102]:
# create dataframe from numpy 

import pandas as pd 

df = pd.DataFrame(dt2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

Numpy creates arrays

In [103]:
np_array = np.array([1, 2, 3])
np_array

array([1, 2, 3])

In [104]:
np_array.dtype

dtype('int32')

In [105]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [106]:
ones.dtype

dtype('float64')

In [107]:
type(ones)

numpy.ndarray

In [108]:
# zeros for change fill the array with 0

zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [109]:
range_array = np.arange(0, 20, 2)
range_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [110]:
# random array for randomize the array

random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[7, 8, 2, 6, 2],
       [8, 6, 1, 3, 9],
       [2, 4, 5, 2, 3]])

In [111]:
random_array.size, random_array.shape

(15, (3, 5))

In [112]:
random_array_r = np.random.random((5,5))
random_array_r

array([[0.5386816 , 0.69011101, 0.23613497, 0.32447228, 0.78625418],
       [0.47793244, 0.17786325, 0.00984966, 0.2495144 , 0.4218658 ],
       [0.1857257 , 0.40937414, 0.92827803, 0.11837442, 0.49737324],
       [0.35656218, 0.72978472, 0.75088491, 0.60230187, 0.87854002],
       [0.80995197, 0.25283264, 0.61126333, 0.14374638, 0.54797842]])

In [113]:
random_array_r.shape

(5, 5)

Array and Matrix

In [114]:
np.unique(random_array)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
dt2[1]

array([4. , 5. , 6.5])

In [117]:
dt3

array([[[1, 2, 4],
        [3, 4, 5],
        [6, 7, 8]],

       [[2, 3, 4],
        [2, 4, 5],
        [3, 5, 6]]])

In [118]:
dt3[:2, :2, :2]

array([[[1, 2],
        [3, 4]],

       [[2, 3],
        [2, 4]]])

In [119]:
dt4 = np.random.randint(10, size=(2, 3, 4, 5))
dt4

array([[[[2, 6, 7, 6, 1],
         [9, 3, 4, 9, 3],
         [4, 1, 8, 1, 9],
         [0, 7, 9, 5, 5]],

        [[9, 4, 6, 5, 6],
         [5, 3, 5, 4, 5],
         [3, 6, 3, 6, 5],
         [0, 5, 5, 0, 1]],

        [[9, 4, 3, 6, 8],
         [2, 3, 3, 0, 0],
         [7, 3, 6, 0, 2],
         [7, 4, 6, 2, 1]]],


       [[[7, 5, 3, 4, 6],
         [5, 8, 9, 4, 1],
         [0, 8, 8, 9, 6],
         [7, 7, 2, 7, 0]],

        [[2, 1, 9, 4, 0],
         [8, 0, 1, 4, 0],
         [1, 7, 8, 5, 7],
         [3, 5, 4, 5, 7]],

        [[8, 8, 5, 3, 5],
         [1, 7, 4, 0, 2],
         [1, 8, 6, 3, 6],
         [1, 8, 8, 9, 4]]]])