Numpy documentation
https://numpy.org/doc/

In [185]:
import numpy as np

Data types & Attributes

In [186]:
# 1-dimensional

dt = np.array([1,2,3])
dt

array([1, 2, 3])

In [187]:
type(dt)

numpy.ndarray

In [188]:
# 2-dimensional 2x3

dt2 = np.array([[1., 2., 3.3],[4., 5., 6.5]])
dt2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [189]:
# 2-dimensional x array 2x3x3

dt3 = np.array([[[1, 2, 4],
               [3, 4, 5],
               [6, 7, 8]],
               
               [[2,3,4],
               [2,4,5],
               [3,5,6]]])
dt3

array([[[1, 2, 4],
        [3, 4, 5],
        [6, 7, 8]],

       [[2, 3, 4],
        [2, 4, 5],
        [3, 5, 6]]])

In [190]:
dt.size, dt2.size, dt3.size

(3, 6, 18)

In [191]:
type(dt), type(dt2), type(dt3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [192]:
# create dataframe from numpy 

import pandas as pd 

df = pd.DataFrame(dt2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

Numpy creates arrays

In [193]:
np_array = np.array([1, 2, 3])
np_array

array([1, 2, 3])

In [194]:
np_array.dtype

dtype('int32')

In [195]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [196]:
ones.dtype

dtype('float64')

In [197]:
type(ones)

numpy.ndarray

In [198]:
# zeros for change fill the array with 0

zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [199]:
range_array = np.arange(0, 20, 2)
range_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [200]:
# random array for randomize the array

random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[9, 3, 8, 8, 2],
       [0, 7, 4, 9, 7],
       [0, 0, 4, 3, 8]])

In [201]:
random_array.size, random_array.shape

(15, (3, 5))

In [202]:
random_array_r = np.random.random((5,5))
random_array_r

array([[0.1368724 , 0.18865234, 0.6608019 , 0.9657263 , 0.36709262],
       [0.37794237, 0.15989161, 0.41572038, 0.06225975, 0.07991925],
       [0.48074413, 0.17035003, 0.84920193, 0.56800331, 0.23839165],
       [0.7772885 , 0.45662929, 0.57951703, 0.80386912, 0.94567953],
       [0.28868918, 0.83573869, 0.1494311 , 0.0689609 , 0.64712741]])

In [203]:
random_array_r.shape

(5, 5)

Array and Matrix

In [204]:
np.unique(random_array)

array([0, 2, 3, 4, 7, 8, 9])

In [205]:
dt2[1]

array([4. , 5. , 6.5])

In [206]:
dt3

array([[[1, 2, 4],
        [3, 4, 5],
        [6, 7, 8]],

       [[2, 3, 4],
        [2, 4, 5],
        [3, 5, 6]]])

In [207]:
dt3[:2, :2, :2]

array([[[1, 2],
        [3, 4]],

       [[2, 3],
        [2, 4]]])

In [208]:
dt4 = np.random.randint(10, size=(2, 3, 4, 5))
dt4

array([[[[0, 6, 9, 6, 5],
         [8, 8, 1, 0, 0],
         [1, 7, 8, 2, 1],
         [5, 9, 2, 6, 1]],

        [[8, 5, 9, 3, 5],
         [2, 5, 9, 4, 6],
         [8, 0, 5, 4, 8],
         [9, 3, 1, 5, 6]],

        [[3, 0, 7, 1, 2],
         [7, 4, 3, 4, 4],
         [1, 7, 8, 9, 8],
         [6, 7, 3, 0, 4]]],


       [[[9, 4, 3, 2, 7],
         [3, 4, 9, 2, 6],
         [5, 1, 3, 7, 2],
         [2, 8, 3, 1, 0]],

        [[4, 8, 6, 7, 4],
         [6, 1, 3, 0, 4],
         [9, 8, 2, 5, 3],
         [5, 6, 2, 4, 9]],

        [[3, 5, 9, 6, 1],
         [7, 5, 9, 7, 3],
         [5, 9, 5, 8, 5],
         [3, 1, 0, 7, 0]]]])

In [209]:
dt4[:, :, :, :1]

array([[[[0],
         [8],
         [1],
         [5]],

        [[8],
         [2],
         [8],
         [9]],

        [[3],
         [7],
         [1],
         [6]]],


       [[[9],
         [3],
         [5],
         [2]],

        [[4],
         [6],
         [9],
         [5]],

        [[3],
         [7],
         [5],
         [3]]]])

Manipulatin array numpy

In [210]:
dt

array([1, 2, 3])

In [211]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [212]:
dt + ones, dt - ones, dt * ones, dt % ones

(array([2., 3., 4.]),
 array([0., 1., 2.]),
 array([1., 2., 3.]),
 array([0., 0., 0.]))

In [213]:
dt * dt2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [214]:
dt2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [215]:
np.square(dt2), dt2 * 2

(array([[ 1.  ,  4.  , 10.89],
        [16.  , 25.  , 42.25]]),
 array([[ 2. ,  4. ,  6.6],
        [ 8. , 10. , 13. ]]))

Aggregation

In [216]:
dlist_list = [1,2,3]
dlist_list

[1, 2, 3]

In [217]:
sum(dlist_list)

6

In [218]:
massive_array = np.random.random(10000)
massive_array.size

10000

In [219]:
massive_array[:10]

array([0.75239374, 0.55135703, 0.97066779, 0.93755093, 0.93152164,
       0.15174239, 0.34082624, 0.84564258, 0.30299717, 0.97592744])

In [221]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

515 µs ± 2.75 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
3.97 µs ± 62.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [222]:
np.max(dt2)

6.5

In [223]:
np.min(dt2)

1.0

In [225]:
np.std(dt2), np.var(dt2)

(1.8226964152656422, 3.3222222222222224)